/* This file was generated by SableCC (http://www.sablecc.org/). */

package texparser.lexer;

import texparser.node.*;

@SuppressWarnings("serial")
public class LexerException extends Exception
{
    private InvalidToken invalidToken;
  
    public LexerException(@SuppressWarnings("hiding") InvalidToken invalidToken, String message)
    {
        super(message);
        this.invalidToken = invalidToken;
    }

    public LexerException(String message)
    {
        this(null, message);
    }
  
    public InvalidToken getToken()
    {
        return this.invalidToken;
    }
}
